### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by Vivi4n** [SMVampire/VVarden#20]
Hey there, trying to launch your bot after initial configuration leaves me with a bit of an issue.

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new Client (/root/VVarden/node_modules/eris/lib/Client.js:206:32)
    at new CommandClient (/root/VVarden/node_modules/eris/lib/command/CommandClient.js:32:9)
    at Object.<anonymous> (/root/VVarden/index.js:63:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

To my understanding it seems to struggle grabbing the relevant discord bot token. As suggested in CONTRIBUTING.md --

`Copy and paste the template.env file and pasted file to .env`

template.env currently exists under a directory .env within the project itself.

Any help would be appreciated (:

**Comment by SMVampire** [comment]
It's been awhile since I've ran this source, but I believe you copy template.env to a file called just `.env`. It can be a little bit of a chore to create it in a windows environment
